[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt"
]

[start]
cmd = "cd backend && uvicorn main_db:app --host 0.0.0.0 --port $PORT"
